Api
Syanom/TestGuru pull request #14
Opened 2021-12-15 15:42 UTC by Syanom

2021-12-15 17:06 UTC, VidgarVii requested changes

2021-12-15 17:06 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    result_url = GistQuestionService.new(@test_completion.current_question).call.html_url
откуда взялся метод html_url Если он не объявлен в GistQuestionService? От куда контроллер про него знает?
Смотри
тут идёт вызов метода call. Это стандартный подход, который можно встретить в любом адекватном проекте.
По соглашению он (call) должен вернуть какой-то результат, который требует дальнейшей обработки.
Вообще частым паттерном для подобных сервисов является такой код
```
result = SomeService.new(...).call или SomeService.call(...)

if result.success?
  ...
else
  ...
end
```

2021-12-15 17:06 UTC, VidgarVii commented on app/helpers/gists_helper.rb
> +    gist.question.body[0, 25]
здесь лучше использовать хелпер `truncate` - [вот небольшой пост про него](https://makandracards.com/makandra/53287-heads-up-rails-offers-two-similar-means-for-text-truncation)

2021-12-15 17:06 UTC, VidgarVii commented on app/helpers/gists_helper.rb
> +    gist.question.body[0, 25]
кстати с последних версиях руби можно так

[...25]

2021-12-15 17:06 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
еще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```

2021-12-15 17:06 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client = Octokit::Client.new(access_token: ENV['GITHUB_GIST_ACCESS_TOKEN'])
если GITHUB_GIST_ACCESS_TOKEN не будет. то ошибка будет на стороне октокит. Что не совсем корректно. Тем более ты эту ошибку зачем-то обрабатываешь. Лучше проверку токена делать явной. Для этого можно воспользоваться 
ENV.fetch('GITHUB_GIST_ACCESS_TOKEN')

2021-12-15 17:06 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client = Octokit::Client.new(access_token: ENV['GITHUB_GIST_ACCESS_TOKEN'])
а как у тебя сюда попадают значения переменных окружений в дев окружении? Не увидел гема для этого

2021-12-15 17:06 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client.create_gist(gist_params)
ни где не пишешь. как пользоваться результатом. Сейчас отдается Responce реализованный внутри гема. И что бы понять как пользоваться сервисом надо лезть в документацию. Код должен быть явным. Все методы должны быть объявлены. Либо в таких случаях оставляют подробный коммент, о том что возвращает метод. Но это не твой случай. По хорошему надо создать объект, который будет возвращать сервис. И он будет содержать нужные методы 
success?, hash, url
Можно воспользоваться структурой https://ruby-doc.org/core-2.5.0/Struct.html

2021-12-15 17:06 UTC, VidgarVii commented on config/application.rb
> +    config.autoload_paths << "#{Rails.root}/lib/clients"
зачем????

2021-12-15 17:06 UTC, VidgarVii commented on app/views/test_completions/show.html.slim
> +p = button_to t('.gist_question'), gists_path(test_completion: { id: @test_completion }), method: :post, class: 'btn btn-light'
так конечно тоже можно, но зачем нам целая форма?
смотри документацию
https://apidock.com/rails/ActionView/Helpers/UrlHelper/button_to
А вот в link_to можно передать метод запроса. Так же как делал ссылку для удаление сессии в прошлом уроке
https://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to

2021-12-15 18:07 UTC, Syanom commented on app/views/test_completions/show.html.slim
> +p = button_to t('.gist_question'), gists_path(test_completion: { id: @test_completion }), method: :post, class: 'btn btn-light'
Изначально тут и была ссылка, может, я ее поменял на кнопку до того, как закоммитил. Кнопка была выбрана из фронтендерских соображений, потому-что красивое :)
Да и в документации к button_to советуют использовать его, когда дело идет о изменении данных в моем приложении, что эта кнопка и делает (ну не меняет, а создает новые):
"This is the safest method to ensure links that cause changes to your data are not triggered by search bots or accelerators."

2021-12-15 18:08 UTC, Syanom commented on config/application.rb
> +    config.autoload_paths << "#{Rails.root}/lib/clients"
Осталось в наследство от урока, удалил

2021-12-15 18:10 UTC, Syanom commented on app/services/gist_question_service.rb
> +  end
Согласен, так лучше

2021-12-15 18:10 UTC, Syanom commented on app/helpers/gists_helper.rb
> +    gist.question.body[0, 25]
Согласен, так лучше

2021-12-15 19:33 UTC, Syanom commented on app/services/gist_question_service.rb
> +    @client = Octokit::Client.new(access_token: ENV['GITHUB_GIST_ACCESS_TOKEN'])
Я просто их инициализирую в том терминале, в котором запускаю консоль/сервер
А какой гем может упростить этот процесс?

2021-12-15 19:34 UTC, Syanom commented on app/services/gist_question_service.rb
> +    @client = Octokit::Client.new(access_token: ENV['GITHUB_GIST_ACCESS_TOKEN'])
Нашел. Кто-то плохо читает задание, хех

2021-12-16 07:24 UTC, VidgarVii commented on Gemfile
> +gem 'dotenv-rails', groups: %i[development test]
в этом файле уже объявлена группа development test

2021-12-16 14:56 UTC, merged