Badges
Syanom/TestGuru pull request #20
Opened 2022-02-10 16:23 UTC by Syanom

2022-02-10 17:07 UTC, VidgarVii requested changes

2022-02-15 07:36 UTC, VidgarVii requested changes

2022-02-15 07:36 UTC, VidgarVii commented on app/models/group.rb
> +class Group < ApplicationRecord
Rule и Group это просто статичные данные. Которые даже изменяться не будут. В базе их хранить точно не стоит. Более чем достаточно использовать какой-нить массив или enum

2022-02-15 07:36 UTC, VidgarVii commented on app/models/rules/attempts.rb
> +class Attempts < Rule
Для чего нужны модели? Вспоминаем первые уроки.
Это инструмент паттерна ActiveRecord (обязательно изучи его). Модель описывает таблицу в базе. Экземпляр класса это запись в таблицы. Еще раз! Модель просто упрощает работу с данными в базе. 
Класть в модели бизнес логику и расписывать там операции это использовать инструменты не по их назначению. Ты будешь забивать гвоздь отверткой или гаечным ключом?
В ДЗ явно сказано. Выдавать бадж после прохождения теста. Так создать такой объект, который будет этим заниматься.

2022-02-15 18:01 UTC, VidgarVii requested changes

2022-02-15 18:01 UTC, VidgarVii commented on app/services/badge_giver_service.rb
> +                    RULES[badge.rule_type].new(badge, test_completion.user).count_badge_allotments)
мне кажется было бы на много проще если бы эти объекты AbstractBadgeRule возвращали true/false
Т.е. мы просто бы задавали вопрос - А заслужил ли текущий юзер данную награду? Простой вопрос - простой ответ. 
Тот же пример из жизни. 
Есть студент (ты) и его работа (PR)
Я (Reviewer) проверяя текущую работу и задаю сам себе простой вопрос стоит ли принимать текущую работу или нет?

2022-02-15 18:01 UTC, VidgarVii commented on app/services/completion.rb
> +    result.min
методы агрегаторы min/max/count/ могут принимать блок.
И можно не использовать each

2022-02-15 18:22 UTC, Syanom commented on app/services/attempts.rb
> +        successful = true if test_completion.successful?
Переменная successful тут отвечает на вопрос: "Среди всех прохождений этого теста этим пользователем, есть ли хоть одно успешное?". Если я буду ей просто присваивать test_completion.successful? , то у меня эта переменная будет отвечать уже на другой вопрос: "Успешно ли последнее прохождение данным пользователем данного теста", что мне не нужно, вот

2022-02-15 18:24 UTC, Syanom commented on app/services/badge_giver_service.rb
> +                    RULES[badge.rule_type].new(badge, test_completion.user).count_badge_allotments)
Это единственное решение, которое мне пришло в голову, чтобы реализовать выдачу множества одинаковых бейджей. Если проверять так, как вы говорите, то у меня будет выдаваться по новому бейджу при каждой новой проверке.

2022-02-15 18:25 UTC, Syanom commented on app/services/attempts.rb
> +class Attempts < AbstractBadgeRule
Не понял, можно по подробнее?

2022-02-15 18:35 UTC, Syanom commented on app/controllers/badge_allotments_controller.rb
> +    @badge_allotments = BadgeAllotment.where(user: current_user).to_a
Тут у меня есть разделение между бейджами и аллотментсами из-за этой строчки в тз: "Пользователь может получать один и тот же бэйдж более одного раза"
Даже если сделать, как вы советуете, придется искать badge_allotment'сы чтобы выводить количество полученных бейджей. А вьюха станет сильно сложнее, придется как-то выводить сначала полученные бейджи, потом все бейджи, при этом убирать из всех те, что получены, чтобы они не выводились 2 раза. В общем, сложно как-то звучит. Да и если у меня тысяча и один бейдж, то юзер будет грузить весь список каждый раз, когда захочет посмотреть на свои 3 с половиной бейджа.

2022-02-16 04:58 UTC, VidgarVii commented on app/services/attempts.rb
> +class Attempts < AbstractBadgeRule
module в ruby. Вспоминай 1 блок

2022-02-16 05:11 UTC, VidgarVii commented on app/services/attempts.rb
> +        successful = true if test_completion.successful?
локальная переменная successful ни на что не отвечает, а просто хранит информацию. И каждую итерацию перезаписывается. 
Если в 1 случаи test_completion.successful? вернёт true, а в других нет. То переменная successful будет true
Получается твоя логика про ВСЕХ похождений этого теста этим пользователем не работает.
Для таких вещей в руби есть метод all? https://apidock.com/ruby/Enumerable/all%3F

А для счётчика count https://apidock.com/ruby/v2_5_5/Enumerable/count

Пиши декларативный код!

2022-02-16 05:13 UTC, VidgarVii commented on app/services/badge_giver_service.rb
> +                    RULES[badge.rule_type].new(badge, test_completion.user).count_badge_allotments)
значит надо сделать так чтобы проверяющий объект проверял есть ли бадж у юзера. Это ведь тоже часть логики выдвать бадж или нет. Всё просто

2022-02-16 05:31 UTC, VidgarVii commented on app/controllers/badge_allotments_controller.rb
> +    @badge_allotments = BadgeAllotment.where(user: current_user).to_a
Вот я и пишу, что такое разделение мб лишним. И всё можно показать на 1 странице. Показывать BadgeAllotment точно не стоит. По ДЗ надо выводить список баджей. А это другая модель. BadgeAllotment это всего-лишь связующая модель м/у юзером и баджами.

> Даже если сделать, как вы советуете, придется искать badge_allotment'сы чтобы выводить количество полученных бейджей

В чём проблема? Ты уже это делаешь, хоть и не совсем оптимальным способом

> Да и если у меня тысяча и один бейдж, то юзер будет грузить весь список каждый раз, когда захочет посмотреть на свои 3 с половиной бейджа

Когда данных становятся много подключают пагинацию. И  всё работает очень быстро и данные грузятся частями. Но сейчас баджей мало. И пагинация не требуется. Если ты покажешь на странице даже десяток объектов ни чего страшного не случится.

> вьюха станет сильно сложнее, придется как-то выводить сначала полученные бейджи, потом все бейджи

Ни разу не станет сложней. если бы сначала попробовал, то убедился что на сложность вью абсолютно бы не повлияло. Так как надо просто отрендерить коллекцию объектов одной и той же модели. Рисуется отдельный партиал для баджей и на странице вызывается рендер коллекций 2 раза
``` ruby
= render @earned_badges
= render @unearned_badges
```
А в контроллере порождаются эти 2 инстанс переменные
И это самое простое решение с которым уже можно работать. 

Способ второй, можно просто вспомнить первые уроки по SQL и не много по гуглив решение
с помощью сортировки сделать так чтобы заработанные баджи были первые в списке. В Postgres это делается с помощью ORDER BY id IN (...), в MySQL функция FIELD
И получилось бы 1 инстанс переменная

Ну и уровень на middle. Смысл тот же но c использованием Arel

```ruby
Test.order(Arel.sql("id IN (#{current_user.tests.ids.join(',')}) desc")).limit(10)
```

> чтобы они не выводились 2 раза
И для этого есть как минимум 3 простых решения.

2022-02-17 08:51 UTC, VidgarVii requested changes

2022-02-17 08:51 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:name, :image_url, :rule_type, :rule_value, :group_type, :group_value)
подумал я над решением группировать несколько правил в один. Хоть я и считаю это не очень хорошим решением, но отказываться от него точно не стоит и можно учесть такой вариант.
Добавление лишних полей только для каких-то индивидуальных правил не очень хорошее решение. Так как например у нас есть 100 различных правил, и для них исопльзуется на 100% только 2 поля rule_type и rule_value. А поля group_type group_value окажутся просто пустыми. Так как они нужны только индивидуально для конкретных правил. Это плохой подход в плане проектирования таблиц. Желательно чтобы все колонки были заполнены данными. 
Предлагаю такой вариант.
Так как решил группировать тесты и проверять общее время прохождения всех тестов этой группы. То эти 2 значения можно считать за параметры правила.
Получается примерно такой метод, который принимает категорию и время
`by_category_and_finished_time(category, finished_time)`
И в таблицу в поле rule_value можно просто писать эти 2 параметра. БД поддерживают массивы.
Вся логика проверки выдачи баджа останется внутри одного объекта, который отвечает за конкретное правило. А не как сейчас, размазана м/у размазаны слоями системы

2022-02-17 08:51 UTC, VidgarVii commented on app/controllers/badges_controller.rb
> +    @unearned_badges = Badge.all - current_user.badges
получилось 3 запроса в базу.
Для unearned_badges можно обойтись 1 запросом в БД. Лишняя сложность. Меньше запросов - быстрей загрузится страница

2022-02-17 08:51 UTC, VidgarVii commented on app/models/badge.rb
> +  belongs_to :author, class_name: 'User'
Сейчас я не против. Но если не будет такого будущего? Парой выходить за рамки тех задания, хуже чем вообще ни чего не делать. Для бизнеса это может быть критично.

2022-02-17 08:51 UTC, VidgarVii commented on app/models/test_completion.rb
> +    BadgeGiverService.new.call(self) if completed?
не исправил

2022-02-17 08:51 UTC, VidgarVii commented on app/services/attempts.rb
> +class Attempts < AbstractBadgeRule
не исправил. Сейчас папка сервисы просто свалка различных классов. Надо навести порядок

2022-02-17 08:51 UTC, VidgarVii commented on app/services/badge_giver_service.rb
> +
Что делают или за что отвечают эти классы в RULES?

2022-02-17 08:51 UTC, VidgarVii commented on app/services/badge_group_service.rb
> +    result
https://apidock.com/ruby/Enumerable/each_with_object

2022-02-19 18:25 UTC, VidgarVii commented on app/services/badge_group_service.rb
> +    result
[each_with_object](https://apidock.com/ruby/Enumerable/each_with_object) а не each_with_index

2022-02-19 23:09 UTC, merged